= MessageChannel

オブザーバパターンライブラリのひとつ. Observable, DRb, MQTT, Redis, Mongo を用いる.  

== 特徴

* スレッドベースのオブザーバパターンライブラリ.
* Obserbable, DRb, MQTT, Redis および Mongo のラッパーとして実装.
* Observer はソケットを使わずに通信できる.
* DRb は外部サーバを使わずにプロセス間通信できる.
* MQTT, Redis, Mongo は通信できるアプリを他言語でも作成できる.
* トピックは文字列として、データは JSON 化した文字列として配信する.

== 導入

アプリの Gemfile にこの行を追加

[source,ruby]
----
gem 'message_channel'
----

それから実行

    $ bundle install

または次のように手動で導入

    $ gem install message_channel
    or
    $ gem install -l message_channel-x.x.x.gem

== 使い方

=== Example 1

[source,ruby]
----
require  "message_channel"

Signal.trap( :INT ) do
  exit
end

channel  =  MessageChannel.new

channel.listen( "hello" ) do |topic, **items|
  p [topic, items]
end

while  true
  channel.notify  "hello", {at: Time.now.to_s}
  sleep  1
end
----

=== Example 2

[source,ruby]
----
require  "message_channel"

Signal.trap( :INT ) do
  exit
end

channel  =  MessageChannel.new

Thread.start do
  while  true
    topic, items  =  channel.listen( "hello" )
    p [topic, items]
  end
end

Thread.start do
  while  true
    channel.notify  "hello", {at: Time.now.to_s}
    sleep  1
  end
end

sleep
----

== リファレンス

=== 条件を指定して、新たな MessageChannel::* を作成する.

[source,ruby]
----
MessageChannel.new( uri = nil, type: nil, host: nil, port: nil, db: nil, size: nil, name: nil )
----

* Result:
  ** MessageChannel::* object.

* Parameter:
  ** uri: scheme://host:port/params (default: nil)
    *** "observer"
    *** "druby://127.0.0.1:8787"
    *** "mqtt://127.0.0.1:1883"
    *** "redis://127.0.0.1:6379/0"
    *** "mongodb://127.0.0.1:27017/test?size=4000&name=_event_queue"
  ** type: Channel type. (default: "observer")
    *** "observer"
    *** "druby"
    *** "mqtt"
    *** "redis"
    *** "mongodb"
  ** host: サービスホスト. (default: nil)
  ** port: サービスポート. (default: nil)
  ** db: データベース名. (default: "test")
  ** size: キューサイズ. (default: 4000)
  ** name: キュー名. (default: "_event_queue")

=== チャネル経由で通知.

[source,ruby]
----
MessageChannel::Observer#notify( topic, **items )
MessageChannel::Druby#notify( topic, **items )
MessageChannel::Mqtt#notify( topic, **items )
MessageChannel::Redis#notify( topic, **items )
MessageChannel::Mongodb#notify( topic, **items )
----

* Result:
  ** nil.

* Parameter:
  ** topic: 通知トピック.
  ** items: 通知アイテム.

=== チャネル経由で通知待機.

[source,ruby]
----
MessageChannel::Observer#listen( *patterns, &block )
MessageChannel::Druby#listen( *patterns, &block )
MessageChannel::Mqtt#listen( *patterns, &block )
MessageChannel::Redis#listen( *patterns, &block )
MessageChannel::Mongodb#listen( *patterns, &block )
----

* Result:
  ** ブロック引数あり: (Non-blocing Mode)
    *** nil.
  ** ブロック引数なし: (Blocking Mode)
    *** topic: 通知トピック.
    *** items: 通知アイテム.

* Parameter:
  ** patterns: マスクパターンの配列.

* Block Parameter:
  ** topic: 通知トピック.
  ** items: 通知アイテム.

=== 通知待機を解除.

[source,ruby]
----
MessageChannel::Observer#unlisten( *patterns )
MessageChannel::Druby#unlisten( *patterns )
MessageChannel::Mqtt#unlisten( *patterns )
MessageChannel::Redis#unlisten( *patterns )
MessageChannel::Mongodb#unlisten( *patterns )
----

* Result:
  ** nil.

* Parameter:
  ** patterns: マスクパターンの配列.

== 貢献

不具合報告とプルリクエストは GitHub https://github.com/arimay/message_channel まで. 

== ライセンス

この Gem は、 http://opensource.org/licenses/MIT[MITライセンス] の条件に基づいてオープンソースとして入手できる.

Copyright (c) ARIMA Yasuhiro <arima.yasuhiro@gmail.com>
